import type { MarketId } from "@/lib/markets/types";
import type { BrokerConfig, BrokerRegion } from "./types";

/**
 * All 23 brokers below are fully visible, searchable, and connectable in the UI —
 * none are hidden or marked "coming soon". `implemented: true` (Dhan only, today)
 * means a real adapter fetches live market data; every other broker still accepts
 * and securely stores real user-entered credentials, it just can't verify them
 * against a live API yet. See lib/brokers/adapters/README for how to promote one
 * of these to a real adapter — it's a JSON entry (already here) plus one adapter
 * class, no UI changes.
 */

export const DHAN_BROKER: BrokerConfig = {
  id: "dhan",
  name: "Dhan",
  monogram: "D",
  region: "india",
  country: "India",
  supportedMarkets: ["NSE", "MCX", "CURRENCY"],
  implemented: true,
  website: "https://dhan.co",
  developerPortal: "https://dhanhq.co",
  documentationUrl: "https://dhanhq.co/docs/v2/",
  authenticationType: "client-id-access-token",
  requiredFields: [
    { key: "clientId", label: "Client ID" },
    { key: "accessToken", label: "Access Token", secret: true },
  ],
  redirectSupported: false,
  websocketSupported: true,
  historicalDataSupported: true,
  paperTradingSupported: false,
  setupTimeMinutes: 5,
  supportedFeatures: ["Live spot & option chain", "Index & stock derivatives", "Websocket streaming"],
  connectButtonLabel: "Connect to Dhan",
  description: "Connect your Dhan account to auto-fill live Spot, CE and PE values.",
  helpLinks: [
    { label: "Get Client ID", url: "https://web.dhan.co" },
    { label: "Generate Access Token", url: "https://web.dhan.co" },
    { label: "View Dhan Developer Docs", url: "https://dhanhq.co/docs/v2/" },
  ],
};

const INDIAN_BROKERS: BrokerConfig[] = [
  DHAN_BROKER,
  {
    id: "zerodha",
    name: "Zerodha Kite",
    monogram: "Z",
    region: "india",
    country: "India",
    supportedMarkets: ["NSE", "MCX", "CURRENCY"],
    implemented: false,
    website: "https://zerodha.com",
    developerPortal: "https://developers.kite.trade",
    documentationUrl: "https://kite.trade/docs/connect/v3/",
    authenticationType: "oauth",
    requiredFields: [
      { key: "apiKey", label: "API Key" },
      { key: "apiSecret", label: "API Secret", secret: true },
    ],
    redirectSupported: true,
    websocketSupported: true,
    historicalDataSupported: true,
    paperTradingSupported: false,
    setupTimeMinutes: 10,
    supportedFeatures: ["Equity & derivatives", "Websocket streaming", "Historical data"],
    connectButtonLabel: "Connect to Zerodha",
    description: "Kite Connect uses an OAuth login redirect — you'll approve access on Zerodha's own site.",
  },
  {
    id: "upstox",
    name: "Upstox",
    monogram: "U",
    region: "india",
    country: "India",
    supportedMarkets: ["NSE", "MCX", "CURRENCY"],
    implemented: false,
    website: "https://upstox.com",
    developerPortal: "https://developer.upstox.com",
    documentationUrl: "https://upstox.com/developer/api-documentation/open-api",
    authenticationType: "oauth",
    requiredFields: [
      { key: "apiKey", label: "API Key" },
      { key: "apiSecret", label: "API Secret", secret: true },
      { key: "redirectUri", label: "Redirect URI" },
    ],
    redirectSupported: true,
    websocketSupported: true,
    historicalDataSupported: true,
    paperTradingSupported: false,
    setupTimeMinutes: 10,
    supportedFeatures: ["Equity & derivatives", "Websocket streaming"],
    connectButtonLabel: "Connect to Upstox",
    description: "Upstox uses OAuth2 authorization-code login via your own registered redirect URI.",
  },
  {
    id: "angelone",
    name: "Angel One",
    monogram: "A",
    region: "india",
    country: "India",
    supportedMarkets: ["NSE", "MCX", "CURRENCY"],
    implemented: false,
    website: "https://www.angelone.in",
    developerPortal: "https://smartapi.angelbroking.com",
    documentationUrl: "https://smartapi.angelbroking.com/docs",
    authenticationType: "session-based",
    requiredFields: [
      { key: "apiKey", label: "API Key" },
      { key: "clientCode", label: "Client Code" },
      { key: "password", label: "Password / PIN", secret: true },
      { key: "totp", label: "TOTP Code", secret: true },
    ],
    redirectSupported: false,
    websocketSupported: true,
    historicalDataSupported: true,
    paperTradingSupported: false,
    setupTimeMinutes: 8,
    supportedFeatures: ["Equity & derivatives", "Websocket streaming"],
    connectButtonLabel: "Connect to Angel One",
    description: "SmartAPI generates a session from your API key plus a fresh TOTP code each login.",
  },
  {
    id: "groww",
    name: "Groww",
    monogram: "G",
    region: "india",
    country: "India",
    supportedMarkets: ["NSE"],
    implemented: false,
    website: "https://groww.in",
    developerPortal: "https://groww.in/trade-api",
    documentationUrl: "https://groww.in/trade-api/docs",
    authenticationType: "api-key-secret",
    requiredFields: [
      { key: "apiKey", label: "API Key" },
      { key: "apiSecret", label: "API Secret / TOTP Secret", secret: true },
    ],
    redirectSupported: false,
    websocketSupported: false,
    historicalDataSupported: true,
    paperTradingSupported: false,
    setupTimeMinutes: 8,
    supportedFeatures: ["Equity trading"],
    connectButtonLabel: "Connect to Groww",
    description: "Groww's Trade API issues a key and secret from its developer console.",
  },
  {
    id: "fyers",
    name: "Fyers",
    monogram: "F",
    region: "india",
    country: "India",
    supportedMarkets: ["NSE", "MCX", "CURRENCY"],
    implemented: false,
    website: "https://fyers.in",
    developerPortal: "https://myapi.fyers.in",
    documentationUrl: "https://myapi.fyers.in/docsv3",
    authenticationType: "oauth",
    requiredFields: [
      { key: "appId", label: "App ID" },
      { key: "secretKey", label: "Secret Key", secret: true },
      { key: "redirectUri", label: "Redirect URI" },
    ],
    redirectSupported: true,
    websocketSupported: true,
    historicalDataSupported: true,
    paperTradingSupported: false,
    setupTimeMinutes: 10,
    supportedFeatures: ["Equity & derivatives", "Websocket streaming", "Historical data"],
    connectButtonLabel: "Connect to Fyers",
    description: "FYERS API v3 uses an OAuth-style auth-code exchange via your registered redirect URI.",
  },
  {
    id: "kotakneo",
    name: "Kotak Neo",
    monogram: "K",
    region: "india",
    country: "India",
    supportedMarkets: ["NSE", "MCX"],
    implemented: false,
    website: "https://www.kotaksecurities.com",
    developerPortal: "https://napi.kotaksecurities.com",
    documentationUrl: "https://napi.kotaksecurities.com/docs",
    authenticationType: "session-based",
    requiredFields: [
      { key: "consumerKey", label: "Consumer Key" },
      { key: "consumerSecret", label: "Consumer Secret", secret: true },
      { key: "mobileNumber", label: "Mobile Number" },
      { key: "password", label: "Password", secret: true },
      { key: "totp", label: "TOTP Code", secret: true },
    ],
    redirectSupported: false,
    websocketSupported: true,
    historicalDataSupported: false,
    paperTradingSupported: false,
    setupTimeMinutes: 10,
    supportedFeatures: ["Equity & derivatives"],
    connectButtonLabel: "Connect to Kotak Neo",
    description: "Kotak Neo generates a session from your consumer key/secret plus a mobile OTP login.",
  },
  {
    id: "icicidirect",
    name: "ICICI Direct",
    monogram: "I",
    region: "india",
    country: "India",
    supportedMarkets: ["NSE", "MCX"],
    implemented: false,
    website: "https://www.icicidirect.com",
    developerPortal: "https://api.icicidirect.com",
    documentationUrl: "https://api.icicidirect.com/breezeapi/documents/index.html",
    authenticationType: "session-based",
    requiredFields: [
      { key: "appKey", label: "App Key" },
      { key: "secretKey", label: "Secret Key", secret: true },
      { key: "sessionToken", label: "Session Token", secret: true },
    ],
    redirectSupported: true,
    websocketSupported: true,
    historicalDataSupported: true,
    paperTradingSupported: false,
    setupTimeMinutes: 10,
    supportedFeatures: ["Equity & derivatives", "Historical data"],
    connectButtonLabel: "Connect to ICICI Direct",
    description: "Breeze API needs a browser login to generate a session token alongside your app key/secret.",
  },
  {
    id: "fivepaisa",
    name: "5paisa",
    monogram: "5",
    region: "india",
    country: "India",
    supportedMarkets: ["NSE", "MCX"],
    implemented: false,
    website: "https://www.5paisa.com",
    developerPortal: "https://www.5paisa.com/developerapi",
    documentationUrl: "https://www.5paisa.com/developerapi/docs",
    authenticationType: "session-based",
    requiredFields: [
      { key: "apiKey", label: "API Key" },
      { key: "clientCode", label: "Client Code" },
      { key: "pin", label: "PIN", secret: true },
    ],
    redirectSupported: false,
    websocketSupported: false,
    historicalDataSupported: false,
    paperTradingSupported: false,
    setupTimeMinutes: 8,
    supportedFeatures: ["Equity & derivatives"],
    connectButtonLabel: "Connect to 5paisa",
    description: "5paisa's OpenAPI issues a client-scoped API key from its developer portal.",
  },
];

const FOREX_BROKERS: BrokerConfig[] = [
  {
    id: "oanda",
    name: "OANDA",
    monogram: "O",
    region: "forex",
    country: "United States",
    supportedMarkets: ["CURRENCY", "GLOBAL"],
    implemented: false,
    website: "https://www.oanda.com",
    developerPortal: "https://developer.oanda.com",
    documentationUrl: "https://developer.oanda.com/rest-live-v20/introduction/",
    authenticationType: "access-token",
    requiredFields: [
      { key: "accessToken", label: "Personal Access Token", secret: true },
      { key: "accountId", label: "Account ID" },
    ],
    redirectSupported: false,
    websocketSupported: true,
    historicalDataSupported: true,
    paperTradingSupported: true,
    setupTimeMinutes: 5,
    supportedFeatures: ["Forex spot & CFDs", "Streaming prices", "Practice accounts"],
    connectButtonLabel: "Connect to OANDA",
    description: "OANDA's v20 API authenticates with a single personal access token from your account.",
  },
  {
    id: "fxcm",
    name: "FXCM",
    monogram: "F",
    region: "forex",
    country: "United Kingdom",
    supportedMarkets: ["CURRENCY"],
    implemented: false,
    website: "https://www.fxcm.com",
    developerPortal: "https://www.fxcm.com/markets/forex-trading-api/",
    documentationUrl: "https://fxcm.github.io/rest-api-docs/",
    authenticationType: "access-token",
    requiredFields: [{ key: "accessToken", label: "Access Token", secret: true }],
    redirectSupported: false,
    websocketSupported: true,
    historicalDataSupported: true,
    paperTradingSupported: true,
    setupTimeMinutes: 5,
    supportedFeatures: ["Forex & CFDs", "Streaming prices"],
    connectButtonLabel: "Connect to FXCM",
    description: "FXCM's REST API authenticates with a bearer access token issued from your account.",
  },
  {
    id: "interactivebrokers",
    name: "Interactive Brokers",
    monogram: "IB",
    region: "forex",
    country: "United States",
    supportedMarkets: ["GLOBAL", "CURRENCY"],
    implemented: false,
    website: "https://www.interactivebrokers.com",
    developerPortal: "https://www.interactivebrokers.com/campus/ibkr-api-page/cpapi-v1/",
    documentationUrl: "https://www.interactivebrokers.com/campus/ibkr-api-page/cpapi-v1/",
    authenticationType: "session-based",
    requiredFields: [],
    redirectSupported: false,
    websocketSupported: true,
    historicalDataSupported: true,
    paperTradingSupported: true,
    setupTimeMinutes: 20,
    supportedFeatures: ["Global equities, options & futures", "Requires IBKR Client Portal Gateway running locally"],
    connectButtonLabel: "Connect to Interactive Brokers",
    description:
      "IBKR's Client Portal API authenticates through a Gateway process you run yourself — there's no simple key/secret pair.",
  },
  {
    id: "alpaca",
    name: "Alpaca",
    monogram: "A",
    region: "forex",
    country: "United States",
    supportedMarkets: ["GLOBAL"],
    implemented: false,
    website: "https://alpaca.markets",
    developerPortal: "https://app.alpaca.markets/signup",
    documentationUrl: "https://docs.alpaca.markets",
    authenticationType: "api-key-secret",
    requiredFields: [
      { key: "apiKeyId", label: "API Key ID" },
      { key: "secretKey", label: "Secret Key", secret: true },
    ],
    redirectSupported: false,
    websocketSupported: true,
    historicalDataSupported: true,
    paperTradingSupported: true,
    setupTimeMinutes: 5,
    supportedFeatures: ["US equities & options", "Paper trading", "Streaming data"],
    connectButtonLabel: "Connect to Alpaca",
    description: "Alpaca issues a Key ID and Secret Key pair — the same credentials work for paper or live trading.",
  },
  {
    id: "tradier",
    name: "Tradier",
    monogram: "T",
    region: "forex",
    country: "United States",
    supportedMarkets: ["GLOBAL"],
    implemented: false,
    website: "https://tradier.com",
    developerPortal: "https://developer.tradier.com",
    documentationUrl: "https://documentation.tradier.com",
    authenticationType: "access-token",
    requiredFields: [
      { key: "accessToken", label: "Access Token", secret: true },
      { key: "accountId", label: "Account ID" },
    ],
    redirectSupported: false,
    websocketSupported: true,
    historicalDataSupported: true,
    paperTradingSupported: true,
    setupTimeMinutes: 5,
    supportedFeatures: ["US equities & options", "Sandbox/paper trading"],
    connectButtonLabel: "Connect to Tradier",
    description: "Tradier authenticates with a bearer access token issued from your developer dashboard.",
  },
];

const CRYPTO_BROKERS: BrokerConfig[] = [
  {
    id: "binance",
    name: "Binance",
    monogram: "B",
    region: "crypto",
    country: "Global",
    supportedMarkets: ["CRYPTO"],
    implemented: false,
    website: "https://www.binance.com",
    developerPortal: "https://www.binance.com/en/binance-api",
    documentationUrl: "https://binance-docs.github.io/apidocs/spot/en/",
    authenticationType: "api-key-secret",
    requiredFields: [
      { key: "apiKey", label: "API Key" },
      { key: "secretKey", label: "Secret Key", secret: true },
    ],
    redirectSupported: false,
    websocketSupported: true,
    historicalDataSupported: true,
    paperTradingSupported: true,
    setupTimeMinutes: 5,
    supportedFeatures: ["Spot & futures", "Websocket streaming", "Testnet"],
    connectButtonLabel: "Connect to Binance",
    description: "Binance API keys are generated directly in your account's API Management page.",
  },
  {
    id: "bybit",
    name: "Bybit",
    monogram: "B",
    region: "crypto",
    country: "Global",
    supportedMarkets: ["CRYPTO"],
    implemented: false,
    website: "https://www.bybit.com",
    developerPortal: "https://www.bybit.com/app/user/api-management",
    documentationUrl: "https://bybit-exchange.github.io/docs/v5/intro",
    authenticationType: "api-key-secret",
    requiredFields: [
      { key: "apiKey", label: "API Key" },
      { key: "secretKey", label: "Secret Key", secret: true },
    ],
    redirectSupported: false,
    websocketSupported: true,
    historicalDataSupported: true,
    paperTradingSupported: true,
    setupTimeMinutes: 5,
    supportedFeatures: ["Spot & derivatives", "Websocket streaming", "Testnet"],
    connectButtonLabel: "Connect to Bybit",
    description: "Bybit API keys are generated directly in your account's API Management page.",
  },
  {
    id: "okx",
    name: "OKX",
    monogram: "O",
    region: "crypto",
    country: "Global",
    supportedMarkets: ["CRYPTO"],
    implemented: false,
    website: "https://www.okx.com",
    developerPortal: "https://www.okx.com/account/my-api",
    documentationUrl: "https://www.okx.com/docs-v5/en/",
    authenticationType: "api-key-secret-passphrase",
    requiredFields: [
      { key: "apiKey", label: "API Key" },
      { key: "secretKey", label: "Secret Key", secret: true },
      { key: "passphrase", label: "Passphrase", secret: true },
    ],
    redirectSupported: false,
    websocketSupported: true,
    historicalDataSupported: true,
    paperTradingSupported: true,
    setupTimeMinutes: 6,
    supportedFeatures: ["Spot & derivatives", "Websocket streaming", "Demo trading"],
    connectButtonLabel: "Connect to OKX",
    description: "OKX requires a Key, Secret, and a Passphrase you set yourself when creating the API key.",
  },
  {
    id: "deribit",
    name: "Deribit",
    monogram: "D",
    region: "crypto",
    country: "Global",
    supportedMarkets: ["CRYPTO"],
    implemented: false,
    website: "https://www.deribit.com",
    developerPortal: "https://www.deribit.com/account/api",
    documentationUrl: "https://docs.deribit.com",
    authenticationType: "api-key-secret",
    requiredFields: [
      { key: "clientId", label: "Client ID" },
      { key: "clientSecret", label: "Client Secret", secret: true },
    ],
    redirectSupported: false,
    websocketSupported: true,
    historicalDataSupported: true,
    paperTradingSupported: true,
    setupTimeMinutes: 5,
    supportedFeatures: ["Options & futures", "Websocket streaming", "Testnet"],
    connectButtonLabel: "Connect to Deribit",
    description: "Deribit issues a Client ID / Client Secret pair from your account's API page.",
  },
  {
    id: "delta",
    name: "Delta Exchange",
    monogram: "Δ",
    region: "crypto",
    country: "India",
    supportedMarkets: ["CRYPTO"],
    implemented: false,
    website: "https://www.delta.exchange",
    developerPortal: "https://www.delta.exchange/app/account/manageapikeys",
    documentationUrl: "https://docs.delta.exchange",
    authenticationType: "api-key-secret",
    requiredFields: [
      { key: "apiKey", label: "API Key" },
      { key: "apiSecret", label: "API Secret", secret: true },
    ],
    redirectSupported: false,
    websocketSupported: true,
    historicalDataSupported: true,
    paperTradingSupported: false,
    setupTimeMinutes: 5,
    supportedFeatures: ["Crypto derivatives", "Websocket streaming"],
    connectButtonLabel: "Connect to Delta Exchange",
    description: "Delta Exchange API keys are generated from your account's API Key management page.",
  },
  {
    id: "bitget",
    name: "Bitget",
    monogram: "B",
    region: "crypto",
    country: "Global",
    supportedMarkets: ["CRYPTO"],
    implemented: false,
    website: "https://www.bitget.com",
    developerPortal: "https://www.bitget.com/api-doc/common/intro",
    documentationUrl: "https://www.bitget.com/api-doc/common/intro",
    authenticationType: "api-key-secret-passphrase",
    requiredFields: [
      { key: "apiKey", label: "API Key" },
      { key: "secretKey", label: "Secret Key", secret: true },
      { key: "passphrase", label: "Passphrase", secret: true },
    ],
    redirectSupported: false,
    websocketSupported: true,
    historicalDataSupported: true,
    paperTradingSupported: true,
    setupTimeMinutes: 6,
    supportedFeatures: ["Spot & futures", "Websocket streaming", "Demo trading"],
    connectButtonLabel: "Connect to Bitget",
    description: "Bitget requires a Key, Secret, and a Passphrase you set yourself when creating the API key.",
  },
  {
    id: "kucoin",
    name: "KuCoin",
    monogram: "K",
    region: "crypto",
    country: "Global",
    supportedMarkets: ["CRYPTO"],
    implemented: false,
    website: "https://www.kucoin.com",
    developerPortal: "https://www.kucoin.com/account/api",
    documentationUrl: "https://docs.kucoin.com",
    authenticationType: "api-key-secret-passphrase",
    requiredFields: [
      { key: "apiKey", label: "API Key" },
      { key: "apiSecret", label: "API Secret", secret: true },
      { key: "apiPassphrase", label: "API Passphrase", secret: true },
    ],
    redirectSupported: false,
    websocketSupported: true,
    historicalDataSupported: true,
    paperTradingSupported: false,
    setupTimeMinutes: 6,
    supportedFeatures: ["Spot & futures", "Websocket streaming"],
    connectButtonLabel: "Connect to KuCoin",
    description: "KuCoin requires a Key, Secret, and a Passphrase you set yourself when creating the API key.",
  },
  {
    id: "kraken",
    name: "Kraken",
    monogram: "K",
    region: "crypto",
    country: "Global",
    supportedMarkets: ["CRYPTO"],
    implemented: false,
    website: "https://www.kraken.com",
    developerPortal: "https://www.kraken.com/u/security/api",
    documentationUrl: "https://docs.kraken.com/rest/",
    authenticationType: "api-key-secret",
    requiredFields: [
      { key: "apiKey", label: "API Key" },
      { key: "privateKey", label: "Private Key", secret: true },
    ],
    redirectSupported: false,
    websocketSupported: true,
    historicalDataSupported: true,
    paperTradingSupported: false,
    setupTimeMinutes: 5,
    supportedFeatures: ["Spot & futures", "Websocket streaming"],
    connectButtonLabel: "Connect to Kraken",
    description: "Kraken issues an API Key and Private Key pair from your account's security settings.",
  },
  {
    id: "coinbase",
    name: "Coinbase",
    monogram: "C",
    region: "crypto",
    country: "Global",
    supportedMarkets: ["CRYPTO"],
    implemented: false,
    website: "https://www.coinbase.com",
    developerPortal: "https://portal.cdp.coinbase.com",
    documentationUrl: "https://docs.cdp.coinbase.com",
    authenticationType: "api-key-secret",
    requiredFields: [
      { key: "apiKeyName", label: "API Key Name" },
      { key: "privateKey", label: "Private Key", secret: true },
    ],
    redirectSupported: false,
    websocketSupported: true,
    historicalDataSupported: true,
    paperTradingSupported: false,
    setupTimeMinutes: 6,
    supportedFeatures: ["Spot trading", "Websocket streaming"],
    connectButtonLabel: "Connect to Coinbase",
    description: "Coinbase Developer Platform issues a named API key with an associated private key.",
  },
];

export const BROKERS: BrokerConfig[] = [...INDIAN_BROKERS, ...FOREX_BROKERS, ...CRYPTO_BROKERS];

export const BROKER_REGIONS: { id: BrokerRegion; label: string }[] = [
  { id: "india", label: "Indian Brokers" },
  { id: "forex", label: "Forex Brokers" },
  { id: "crypto", label: "Crypto Exchanges" },
  { id: "global", label: "Global Brokers" },
];

export function getBrokersForMarket(marketId: MarketId): BrokerConfig[] {
  return BROKERS.filter((broker) => broker.supportedMarkets.includes(marketId));
}

export function getBrokerById(brokerId: string): BrokerConfig | undefined {
  return BROKERS.find((broker) => broker.id === brokerId);
}

export function getBrokersByRegion(region: BrokerRegion): BrokerConfig[] {
  return BROKERS.filter((broker) => broker.region === region);
}

export function searchBrokers(query: string): BrokerConfig[] {
  const q = query.trim().toLowerCase();
  if (!q) return BROKERS;
  return BROKERS.filter(
    (broker) => broker.name.toLowerCase().includes(q) || broker.id.toLowerCase().includes(q),
  );
}
