import type { DataQuality, MetricId } from "@/lib/context/types";

/** Bumped whenever the STRUCTURE of a generated explanation changes (a
 *  field renamed/added/removed, or a template's meaning changes) — never
 *  for routine data changes. Lets a consumer (the dev panel, a future
 *  export) detect "this explanation was generated by an older version of
 *  the engine" without guessing from content. */
export const EXPLANATION_VERSION = "1.0.0";

export type MetricExplanation = {
  metric: MetricId;
  title: string;
  summary: string;
  calculationBasis: string;
  observedChange: string;
  limitations: string[];
  dataQuality: DataQuality;
};
